apiVersion: v1
kind: Service
metadata:
  name: {{ include "database.fullname" . }}-svc
  labels:
    {{- include "database.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.portName }}
      protocol: TCP
      name: {{ .Values.service.portName }}
  selector:
    {{- include "database.selectorLabels" . | nindent 4 }}
