apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "certificate.name" . }}
spec:
  secretName: {{ include "certificate.name" .}}
  dnsNames:
    {{- range .Values.hosts }}
    - {{ . | quote }}
    {{- end }}
  issuerRef:
    name: {{ .Values.issuer }}
    kind: ClusterIssuer