# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
pipelines:
  branches:
    master:
      - step:
          name: Build helm repo
          deployment: production
          image: dtzar/helm-kubectl:3.4.0
          script:
            - mkdir -p tmp/charts
            - helm package . --destination tmp/charts
            - helm repo index .
            - export access_token=$(curl -s -X POST -u "${CLIENT_ID}:${CLIENT_SECRET}" \
              https://bitbucket.org/site/oauth2/access_token \
              -d grant_type=client_credentials -d scopes="repository"| jq --raw-output '.access_token')
            - >
              curl -X POST -H "Authorization: Bearer $access_token" \
                https://api.bitbucket.org/2.0/repositories/"${BITBUCKET_WORKSPACE}"/"${BITBUCKET_REPO_FULL_NAME}"/downloads \
                -F files=@tmp/charts/