# Default values for kuhdo-app.
# This is a YAML-formatted file.

# Environments descriptions
# enable only one of those
tags:
  production: false
  staging: false
  dynamic: false
  local: true

# Application namespace
# global namespace links to namespace: but is
# also available for sub charts
global:
  namespace: kuhdo-portal-test-2
# this is for the parent chart
namespace: |-
  {{ .Values.global.namespace }}
# deployment replicaCount of pod
replicaCount: 1
# meta data for selectors
nameOverride: "kuhdo-webapp"
fullnameOverride: "kuhdo-webapp"

# pod container configuration
containers:
  # name of the container
  web:
    # image and version of the container
    repository: kuhdo/web
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"
    # live- and readiness probe is only set  if
    # the container has a port list entry
    port: 80
  app:
    repository: kuhdo/app
    pullPolicy: Always
    tag: "1.4.2"
    port: 9000
    args: "prod"
  queue:
    repository: kuhdo/app
    pullPolicy: IfNotPresent
    tag: "1.4.2"
    args: "queue"
  scheduler:
    repository: kuhdo/app
    pullPolicy: IfNotPresent
    tag: "1.4.2"
    args: "scheduler"
  websockets:
    repository: kuhdo/app
    pullPolicy: IfNotPresent
    tag: "1.4.2"
    args: "websockets"

# Configmap for laravel app container
dotenv:
  APP_DEBUG: "false"
  APP_ENV: "production"
  APP_LOG_LEVEL: "debug"
  APP_LOG_CHANNEL: "errorlog"
  APP_NAME: "KUHdo GmbH"
  APP_URL: "https://portal.kuhdo.de"
  BROADCAST_DRIVER: "redis"
  CACHE_DRIVER: "redis"
  QUEUE_DRIVER: "redis"
  SESSION_DRIVER: "redis"
  SESSION_DOMAIN: ".portal.kuhdo.de"
  SESSION_CONNECTION: "redis"
  DB_CONNECTION: "mariadb"
  DB_HOST: "database-svc"
  DB_PORT: "3306"
  REDIS_HOST: "redis-svc"
  REDIS_PORT: "6379"
  REDIS_CLIENT: "phpredis"
  MAIL_MAILER: "mailgun"
  MAIL_HOST: "api.eu.mailgun.org"
  MAIL_NAME: "KUHdo"
  MAIL_PORT: 587
  MAIL_USERNAME: "portal@email.kuhdo.de"
  MAIL_FROM_ADDRESS: "no-reply@kuhdo.de"
  MAIL_ENCRYPTION: "tls"
  MAILGUN_DOMAIN: "email.kuhdo.de"
  MAILGUN_ENDPOINT: "api.eu.mailgun.net"
  TELESCOPE_REQUEST_WATCHER: "false"
  TELESCOPE_ENABLED: "false"
  EEX_SFTP_HOST: "sftp.datasource.eex-group.com"
  MIX_VUE_APP_I18N_LOCALE: "de"
  MIX_VUE_APP_I18N_FALLBACK_LOCALE: "en"

# Secrets for the laravel app container
secrets:
  APP_KEY: base64:sh8FW+fW3s62e8gg1LVwojlNP0wruH54/WAhsFnye3U=
  EEX_SFTP_PASSWORD: supersecret
  EEX_SFTP_REMOTE_PATH: /F:/EEX_Production/master/market_data/agricultural
  EEX_SFTP_USERNAME: EEX_6..
  LOG_SLACK_WEBHOOK_URL: supersecret
  MAILGUN_SECRET: key-a05395e...
  MAIL_PASSWORD: test123
  MIX_STRIPE_KEY: supersecret
  MIX_STRIPE_SECRET: supersecret
  SLACK_WEBHOOK_URL: supersecret
  STRIPE_KEY: supersecret
  STRIPE_SECRET: supersecret
  STRIPE_TAX_RATE: txr_1EPpn...
  STRIPE_USER_PLAN: plan_DNd...1

# docker registry credentials to be created regcred
imageCredentials:
  registry: docker.io
  username: arneba
  password: 7a3d0665-0f1a-47a6-9167-b877b9ea7def
  email: Arne.Bartelt@kuhdo.de
#  Map of pull secrets if there are different for the images
imagePullSecrets:
  - name: regcred

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  annotations:
     #kubernetes.io/ingress.class: traefik
     kubernetes.io/tls-acme: "true"
  hosts:
    - host: dev.kuhdo.local
      paths: [/]
      port: 80
      name: web
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Dependency values
database:
  enabled: true
redis:
  enabled: true
  service:
    annotations: { }
  serviceType: Nodeport
  securityContext:
    enabled: false
  ## Cluster settings
  cluster:
    enabled: true
    slaveCount: 3
  metrics:
    enabled: true
    # resources: {}
    # podAnnotations: {}
    # targetServiceAnnotations:
    #   prometheus.io/scrape: "true"
    #   prometheus.io/port: "9121"

  ##
  ## Redis Master parameters
  ##
  master:
    ## Use password authentication
    port: 6379
    ## Redis Master pod annotations
    podAnnotations: { }
    ## Redis Master Service properties
    service:
      ##  Redis Master Service type
      type: NodePort
      annotations: { }

  ##
  ## Redis Slave properties
  ## Note: serviceType and service are mandatory parameters
  ## The rest of the parameters, if undefined, will inherit those declared in Redis Master
  ##
  slave:
    ## Slave Service properties
    service:
      ## Redis Slave Service type
      type: NodePort
      annotations: { }
      loadBalancerIP: