apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}-svc
  labels:
  {{- include "redis.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: {{ .Chart.Name }}
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
