apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Values.global.namespace }}
  name: {{ include "redis.fullname" . }}
  labels:
  {{- include "redis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
  {{- include "redis.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "redis.fullname" . }}-svc
  template:
    metadata:
      namespace: {{ .Values.global.namespace }}
      {{- with .Values.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
    {{- include "redis.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: {{ include "redis.fullname" . }}-storage
              mountPath: /data
      volumes:
        - name: {{ include "redis.fullname" . }}-storage
          persistentVolumeClaim:
            claimName: {{ include "redis.fullname" . }}-redis-pv-claim