apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "helm-webapp.fullname" . }}-pv-claim
  labels:
  {{- include "helm-webapp.labels" . | nindent 4 }}
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi