apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJWakNCL3FBREFnRUNBZ0VBTUFvR0NDcUdTTTQ5QkFNQ01DTXhJVEFmQmdOVkJBTU1HR3N6Y3kxelpYSjIKWlhJdFkyRkFNVFl3TmpFME1EWTROREFlRncweU1ERXhNak14TkRFeE1qUmFGdzB6TURFeE1qRXhOREV4TWpSYQpNQ014SVRBZkJnTlZCQU1NR0dzemN5MXpaWEoyWlhJdFkyRkFNVFl3TmpFME1EWTROREJaTUJNR0J5cUdTTTQ5CkFnRUdDQ3FHU000OUF3RUhBMElBQkVrY0E4eTNzNlcvUHNCb0Znd3M1OWlmMnlScVBIMWx1QWtvMllvbS9ITHgKQXVOZHFDUC9wOXJKeXlPYU93N0lpVU9vMmFMNlliS0dvZUNCQjBSZEdPbWpJekFoTUE0R0ExVWREd0VCL3dRRQpBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUhBRjlQQmN0dmNtCjhSOTZKU00vb1UwVFVXdGVwdVdZcDk3Z0ljUW1UbEtrQWlBZkgvbGJkU295T0NEQTg4SXJzT2VrTWlJamZRZFQKMVBzcHhmRDAvRnVBUlE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://master.kuhdo.dev:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    password: 27488e0ebc028081800b05b3f11bd916
    username: admin
