apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mcsql.fullname" . }}
  labels: {{- include "mcsql.labels" . | nindent 4 }}
data:
  PREFIX: {{ .Values.file.prefix | b64enc | quote }}
  RM_OLDER_THAN: {{ .Values.file.rmOlderThan | b64enc | quote }}
  MYSQL_HOST: {{ .Values.mysql.host | b64enc | quote }}
  MYSQL_PORT: {{ .Values.mysql.port | b64enc | quote }}
  S3_HOST: {{ .Values.s3.host | b64enc | quote }}
  S3_BUCKET: {{ .Values.s3.bucket | b64enc | quote }}

