apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mcsql.fullname" . }}
  labels: {{- include "mcsql.labels" . | nindent 4 }}
data:
  {{- if .Values.mysql.user }}
  MYSQL_USER: {{ .Values.mysql.user | b64enc | quote }}
  {{- end }}
  MYSQL_PASSWORD: {{ .Values.mysql.password | b64enc | quote }}
  S3_KEY: {{ .Values.s3.key | b64enc | quote }}
  S3_SECRET: {{ .Values.s3.secret | b64enc | quote }}