apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-webapp.fullname" . }}
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.replicaCount}}
  minReadySeconds: 10
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
  selector:
    matchLabels:
  {{- include "helm-webapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
    {{- include "helm-webapp.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      initContainers:
        - image: "{{ .Values.containers.app.repository}}:{{ .Values.containers.app.tag | default .Chart.AppVersion }}"
          name: artisan
          imagePullPolicy: Always
          command:
            - /bin/sh
            - -c
            - php artisan migrate --force;
            - php artisan route:cache ;
            - php artisan view:clear ;
            - php artisan db:seed --force --class RolesPermissions ;
            - php artisan kuhdo:courses:current ;
            - php artisan horizon:terminate ;
          env:
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: webapp-env-secrets
                  key: APP_KEY
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: database-user-creds
                  key: MYSQL_DATABASE
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-user-creds
                  key: MYSQL_PASSWORD
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-user-creds
                  key: MYSQL_USER
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: webapp-env-secrets
                  key: MAIL_PASSWORD
            - name: MAILGUN_SECRET
              valueFrom:
                secretKeyRef:
                  name: webapp-env-secrets
                  key: MAILGUN_SECRET
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: webapp-env-secrets
                  key: STRIPE_KEY
            - name: STRIPE_SECRET
              valueFrom:
                secretKeyRef:
                  name: webapp-env-secrets
                  key: STRIPE_SECRET
            - name: MIX_STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: webapp-env-secrets
                  key: MIX_STRIPE_KEY
            - name: MIX_STRIPE_SECRET
              valueFrom:
                secretKeyRef:
                  name: webapp-env-secrets
                  key: MIX_STRIPE_SECRET
            - name: STRIPE_USER_PLAN
              valueFrom:
                secretKeyRef:
                  name: webapp-env-secrets
                  key: STRIPE_USER_PLAN
            - name: STRIPE_TAX_RATE
              valueFrom:
                secretKeyRef:
                  name: webapp-env-secrets
                  key: STRIPE_TAX_RATE
            - name: EEX_SFTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: webapp-env-secrets
                  key: EEX_SFTP_USERNAME
            - name: EEX_SFTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: webapp-env-secrets
                  key: EEX_SFTP_PASSWORD
            - name: EEX_SFTP_REMOTE_PATH
              valueFrom:
                secretKeyRef:
                  name: webapp-env-secrets
                  key: EEX_SFTP_REMOTE_PATH
            - name: LOG_SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: webapp-env-secrets
                  key: LOG_SLACK_WEBHOOK_URL
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: webapp-env-secrets
                  key: SLACK_WEBHOOK_URL
          envFrom:
            - configMapRef:
                name: kuhdo-portal-config
          {{ if .Values.tags.dynamic }}
        - image: "{{ .Values.containers.app.repository}}:{{ .Values.containers.app.tag | default .Chart.AppVersion }}"
          name: artisan-dynamic
          imagePullPolicy: Always
          command:
            - /bin/sh
            - -c
            - php artisan db:wipe --force ;
            - php artisan migrate --seed --env=local ;
          env:
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: webapp-env-secrets
                  key: APP_KEY
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: database-user-creds
                  key: MYSQL_DATABASE
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-user-creds
                  key: MYSQL_PASSWORD
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-user-creds
                  key: MYSQL_USER
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: webapp-env-secrets
                  key: MAIL_PASSWORD
            - name: MAILGUN_SECRET
              valueFrom:
                secretKeyRef:
                  name: webapp-env-secrets
                  key: MAILGUN_SECRET
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: webapp-env-secrets
                  key: STRIPE_KEY
            - name: STRIPE_SECRET
              valueFrom:
                secretKeyRef:
                  name: webapp-env-secrets
                  key: STRIPE_SECRET
            - name: MIX_STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: webapp-env-secrets
                  key: MIX_STRIPE_KEY
            - name: MIX_STRIPE_SECRET
              valueFrom:
                secretKeyRef:
                  name: webapp-env-secrets
                  key: MIX_STRIPE_SECRET
            - name: STRIPE_USER_PLAN
              valueFrom:
                secretKeyRef:
                  name: webapp-env-secrets
                  key: STRIPE_USER_PLAN
            - name: STRIPE_TAX_RATE
              valueFrom:
                secretKeyRef:
                  name: webapp-env-secrets
                  key: STRIPE_TAX_RATE
            - name: EEX_SFTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: webapp-env-secrets
                  key: EEX_SFTP_USERNAME
            - name: EEX_SFTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: webapp-env-secrets
                  key: EEX_SFTP_PASSWORD
            - name: EEX_SFTP_REMOTE_PATH
              valueFrom:
                secretKeyRef:
                  name: webapp-env-secrets
                  key: EEX_SFTP_REMOTE_PATH
            - name: LOG_SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: webapp-env-secrets
                  key: LOG_SLACK_WEBHOOK_URL
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: webapp-env-secrets
                  key: SLACK_WEBHOOK_URL
          envFrom:
            - configMapRef:
                name: kuhdo-portal-config
          {{end}}
      containers:
        {{- range $key, $config := .Values.containers }}
        - name: {{ $key }}
          image: "{{ $config.repository }}:{{ $config.tag }}"
          imagePullPolicy: {{ $config.pullPolicy }}
          {{ if $config.args }}
          args: [{{ $config.args | quote}}]
          {{end}}
          {{ if $config.port }}
          ports:
            - containerPort: {{ $config.port }}
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            tcpSocket:
              port: {{ $config.port }}
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 15
            tcpSocket:
              port: {{ $config.port }}
            timeoutSeconds: 30
          {{ end }}
          {{ if eq $key "web"}}
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - wget -t 5 -O- --post-data='"localhost:9000"' --header="Content-Type:application/json" http://localhost:2019/config/apps/http/servers/srv0/routes/3/handle/0/upstreams/0/dial/
          {{ end }}
          resources: { }
          {{ if ne $key "web" }}
          env:
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: webapp-env-secrets
                  key: APP_KEY
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: database-user-creds
                  key: MYSQL_DATABASE
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-user-creds
                  key: MYSQL_PASSWORD
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-user-creds
                  key: MYSQL_USER
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: webapp-env-secrets
                  key: MAIL_PASSWORD
            - name: MAILGUN_SECRET
              valueFrom:
                secretKeyRef:
                  name: webapp-env-secrets
                  key: MAILGUN_SECRET
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: webapp-env-secrets
                  key: STRIPE_KEY
            - name: STRIPE_SECRET
              valueFrom:
                secretKeyRef:
                  name: webapp-env-secrets
                  key: STRIPE_SECRET
            - name: MIX_STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: webapp-env-secrets
                  key: MIX_STRIPE_KEY
            - name: MIX_STRIPE_SECRET
              valueFrom:
                secretKeyRef:
                  name: webapp-env-secrets
                  key: MIX_STRIPE_SECRET
            - name: STRIPE_USER_PLAN
              valueFrom:
                secretKeyRef:
                  name: webapp-env-secrets
                  key: STRIPE_USER_PLAN
            - name: STRIPE_TAX_RATE
              valueFrom:
                secretKeyRef:
                  name: webapp-env-secrets
                  key: STRIPE_TAX_RATE
            - name: EEX_SFTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: webapp-env-secrets
                  key: EEX_SFTP_USERNAME
            - name: EEX_SFTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: webapp-env-secrets
                  key: EEX_SFTP_PASSWORD
            - name: EEX_SFTP_REMOTE_PATH
              valueFrom:
                secretKeyRef:
                  name: webapp-env-secrets
                  key: EEX_SFTP_REMOTE_PATH
            - name: LOG_SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: webapp-env-secrets
                  key: LOG_SLACK_WEBHOOK_URL
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: webapp-env-secrets
                  key: SLACK_WEBHOOK_URL
          envFrom:
            - configMapRef:
                name: kuhdo-portal-config
          {{ end }}
          {{- end }}