apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.global.namespace }}
  name: webapp-env-secrets
type: Opaque
data:
  APP_KEY: {{ .Values.secrets.APP_KEY | b64enc }}
  EEX_SFTP_PASSWORD: {{ .Values.secrets.EEX_SFTP_PASSWORD | b64enc }}
  EEX_SFTP_REMOTE_PATH: {{ .Values.secrets.EEX_SFTP_REMOTE_PATH | b64enc }}
  EEX_SFTP_USERNAME: {{ .Values.secrets.EEX_SFTP_USERNAME | b64enc }}
  LOG_SLACK_WEBHOOK_URL: {{ .Values.secrets.LOG_SLACK_WEBHOOK_URL | b64enc }}
  MAIL_PASSWORD: {{ .Values.secrets.MAIL_PASSWORD | b64enc }}
  MAILGUN_SECRET: {{ .Values.secrets.MAILGUN_SECRET | b64enc }}
  MIX_STRIPE_KEY: {{ .Values.secrets.MIX_STRIPE_KEY | b64enc }}
  MIX_STRIPE_SECRET: {{ .Values.secrets.MIX_STRIPE_SECRET | b64enc }}
  SLACK_WEBHOOK_URL: {{ .Values.secrets.SLACK_WEBHOOK_URL | b64enc }}
  STRIPE_KEY: {{ .Values.secrets.STRIPE_KEY | b64enc }}
  STRIPE_SECRET: {{ .Values.secrets.STRIPE_SECRET | b64enc }}
  STRIPE_TAX_RATE: {{ .Values.secrets.STRIPE_TAX_RATE | b64enc }}
  STRIPE_USER_PLAN: {{ .Values.secrets.STRIPE_USER_PLAN | b64enc }}
---
apiVersion: v1
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
kind: Secret
metadata:
  name: regcred
  namespace: {{ .Values.global.namespace }}
type: kubernetes.io/dockerconfigjson