apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.global.namespace }}
  name: {{ include "helm-webapp.fullname" . | lower | nospace }}-web
  labels:
    {{- include "helm-webapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helm-webapp.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.global.namespace }}
  name: {{ include "helm-webapp.fullname" .  | kebabcase }}-app
  labels:
  {{- include "helm-webapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9000
      protocol: TCP
      name: php
  selector:
  {{- include "helm-webapp.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.global.namespace }}
  name: {{ include "helm-webapp.fullname" . | kebabcase }}-websockets
  labels:
  {{- include "helm-webapp.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 6001
      protocol: TCP
      name: websockets
  selector:
  {{- include "helm-webapp.selectorLabels" . | nindent 4 }}