apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: kuhdo-portal-web-svc
  labels:
    app: kuhdo-portal-webapp
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: kuhdo-portal-webapp
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: kuhdo-portal-app-svc
  labels:
    app: kuhdo-portal-webapp
spec:
  ports:
    - port: 9000
      protocol: TCP
  selector:
    app: kuhdo-portal-webapp
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: kuhdo-portal-websockets-svc
  labels:
    app: kuhdo-portal-webapp
spec:
  type: NodePort
  ports:
    - port: 6001
      protocol: TCP
  selector:
    app: kuhdo-portal-webapp