{{- if .Values.ingress.enabled }}
{{- $fullName := include "helm-webapp.fullname" . }}
{{- if .Values.ingress.tls }}
{{- range .Values.ingress.tls }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $fullName }}
spec:
  secretName: {{ .secretName }}
  dnsNames:
    {{- range .hosts }}
    - {{ . | quote }}
    {{- end }}
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
{{- end }}
{{- end }}
{{- end }}