apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-webapp.fullname" . }}-config
data:
  APP_DEBUG: {{ .Values.dotenv.APP_DEBUG | default false  | quote }}
  APP_ENV: {{ .Values.dotenv.APP_ENV  | default "production" | quote }}
  APP_LOG_LEVEL: {{ .Values.dotenv.APP_LOG_LEVEL  | default "debug" | quote }}
  APP_LOG_CHANNEL: {{ .Values.dotenv.APP_LOG_CHANNEL  | default "errorlog" | quote }}
  APP_NAME: {{ .Values.dotenv.APP_NAME  | default "KUHdo Gmbh" | quote}}
  APP_URL: {{ .Values.dotenv.APP_URL | default "https://portal.kuhdo.de" | quote }}
  LOG_CHANNEL: {{ .Values.dotenv.APP_LOG_CHANNEL  | default "errorlog" | quote }}
  BROADCAST_DRIVER: {{ .Values.dotenv.BROADCAST_DRIVER | default "redis"  | quote }}
  CACHE_DRIVER: {{ .Values.dotenv.CACHE_DRIVER  | default "redis" | quote }}
  QUEUE_DRIVER: {{ .Values.dotenv.QUEUE_DRIVER  | default "redis" | quote }}
  SESSION_DRIVER: {{ .Values.dotenv.SESSION_DRIVER  | default "redis" | quote }}
  SESSION_DOMAIN: {{ .Values.dotenv.SESSION_DOMAIN  | quote }}
  SESSION_CONNECTION: {{ .Values.dotenv.SESSION_CONNECTION  | default "redis"  | quote }}
  DB_CONNECTION: {{ .Values.dotenv.DB_CONNECTION  | default "mariadb" | quote }}
  DB_HOST: {{- if eq (include "prodstaging" .) "true" }} "database" {{- else }} "database-svc" {{- end }}
  DB_PORT: {{ .Values.dotenv.DB_PORT | default 3306 | quote }}
  REDIS_HOST: {{- if eq (include "prodstaging" .) "true" }} "redis-master" {{- else }} "redis-svc" {{- end }}
  REDIS_PORT: {{ .Values.dotenv.REDIS_PORT | default 6379 | quote }}
  REDIS_CLIENT: {{ .Values.dotenv.REDIS_CLIENT | default "phpredis" | quote }}
  MAIL_MAILER: {{ .Values.dotenv.MAIL_MAILER | quote }}
  MAIL_HOST: {{ .Values.dotenv.MAIL_HOST | quote }}
  MAIL_NAME: {{ .Values.dotenv.MAIL_NAME | quote }}
  MAIL_PORT: {{ .Values.dotenv.MAIL_PORT | quote }}
  MAIL_USERNAME: {{ .Values.dotenv.MAIL_USERNAME  | quote}}
  MAIL_FROM_ADDRESS: {{ .Values.dotenv.MAIL_FROM_ADDRESS  | quote}}
  MAIL_ENCRYPTION: {{ .Values.dotenv.MAIL_ENCRYPTION  | quote}}
  MAILGUN_DOMAIN: {{ .Values.dotenv.MAILGUN_DOMAIN  | quote}}
  MAILGUN_ENDPOINT: {{ .Values.dotenv.MAILGUN_ENDPOINT  | quote}}
  TELESCOPE_REQUEST_WATCHER: {{ .Values.dotenv.TELESCOPE_REQUEST_WATCHER  | quote}}
  TELESCOPE_ENABLED: {{ .Values.dotenv.TELESCOPE_ENABLED  | quote}}
  EEX_SFTP_HOST: {{ .Values.dotenv.EEX_SFTP_HOST  | quote}}
  TRUST_PROXY: {{ .Values.dotenv.TRUST_PROXY |default "*" | quote }}
  PUSHER_APP_ID: {{ .Values.dotenv.PUSHER_APP_ID | default (include "helm-webapp.fullname" .) | quote }}
  PUSHER_APP_KEY: {{ .Values.dotenv.PUSHER_APP_KEY | default (include "helm-webapp.fullname" .) | quote }}
  PUSHER_KEY: {{ .Values.dotenv.PUSHER_APP_KEY | default (include "helm-webapp.fullname" .) | quote }}
  PUSHER_ENDPOINT: {{ .Values.ingressRouteTCP.hosts.websocket.host }}
  PUSHER_ENDPOINT_SCHEME: {{ .Values.dotenv.PUSHER_ENDPOINT_SCHEME | default "https" | quote }}
  PUSHER_ENDPOINT_PORT: {{ .Values.ingressRouteTCP.hosts.websocket.port | default "6001" | quote }}
  PUSHER_FORCE_TLS: {{ .Values.dotenv.PUSHER_FORCE_TLS | default "true" | quote }}
  ECHO_ENCRYPTED: {{ .Values.dotenv.ECHO_ENCRYPTED | default "true" | quote }}
  PUSHER_HOST: {{ (include "helm-webapp.fullname" .) }}-websocket
  PUSHER_APP_CLUSTER: {{ .Values.dotenv.PUSHER_APP_CLUSTER | default "" | quote }}