apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-webapp.fullname" . }}
  annotations:
    rollme: {{ randAlphaNum 5 | quote }}
spec:
  replicas: {{ .Values.replicaCount}}
  minReadySeconds: 10
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.replicaMaxSurge }}
      maxUnavailable: {{ .Values.replicamaxUnavailable }}
  selector:
    matchLabels:
  {{- include "helm-webapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
    {{- include "helm-webapp.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      initContainers:
        - image: "{{ .Values.containers.app.repository}}:{{ .Values.containers.app.tag | default .Chart.AppVersion }}"
          name: artisan
          imagePullPolicy: Always
          command:
            - /bin/sh
            - -c
            - php artisan migrate --force;
            - php artisan route:cache ;
            - php artisan view:clear ;
            - php artisan db:seed --force --class RolesPermissions ;
            - php artisan kuhdo:courses:current ;
            - php artisan horizon:terminate ;
            {{ if .Values.tags.dynamic}}
            - php artisan db:wipe ;
            - php artisan migrate --seed --env=local ;
            - php artisan storage:link ;
          {{ end }}
          env:
            {{- range $key, $value := .Values.secrets.webapp }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm-webapp.fullname" $ }}-env-secrets
                  key: {{ $key }}
            {{ end -}}
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm-webapp.fullname" $ }}-db-user-creds
                  key: MYSQL_DATABASE
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm-webapp.fullname" $ }}-db-user-creds
                  key: MYSQL_PASSWORD
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm-webapp.fullname" $ }}-db-user-creds
                  key: MYSQL_USER
            {{ if eq (include "prodstaging" .) "true" -}}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm-webapp.fullname" $ }}-redis
                  key: redis-password
            {{ end }}
          envFrom:
            - configMapRef:
                name: {{ include "helm-webapp.fullname" . }}-config
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        {{- range $key, $config := .Values.containers }}
        - name: {{ $key }}
          image: "{{ $config.repository }}:{{ $config.tag }}"
          imagePullPolicy: {{ $config.pullPolicy }}
          {{ if $config.args }}
          args: [{{ $config.args | quote}}]
          {{end}}
          {{ if $config.port }}
          ports:
            - name: {{ $config.portName }}
              containerPort: {{ $config.port }}
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            tcpSocket:
              port: {{ $config.port }}
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 15
            tcpSocket:
              port: {{ $config.port }}
            timeoutSeconds: 30
          {{ end }}
          {{ if eq $key "web"}}
          env:
            - name: PHP_UP_STREAM_HOST
              value: "localhost"
            - name: PHP_UP_STREAM_PORT
              value: "9000"
          volumeMounts:
            - name: {{ include "helm-webapp.fullname" $ }}-storage
              mountPath: storage
          {{ end }}
          resources: { }
          {{ if ne $key "web" }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: {{ include "helm-webapp.fullname" $ }}-storage
              mountPath: src/storage/app/
          env:
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm-webapp.fullname" $ }}-env-secrets
                  key: APP_KEY
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm-webapp.fullname" $ }}-db-user-creds
                  key: MYSQL_DATABASE
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm-webapp.fullname" $ }}-db-user-creds
                  key: MYSQL_PASSWORD
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm-webapp.fullname" $ }}-db-user-creds
                  key: MYSQL_USER
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm-webapp.fullname" $ }}-env-secrets
                  key: MAIL_PASSWORD
            - name: MAILGUN_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm-webapp.fullname" $ }}-env-secrets
                  key: MAILGUN_SECRET
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm-webapp.fullname" $ }}-env-secrets
                  key: STRIPE_KEY
            - name: STRIPE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm-webapp.fullname" $ }}-env-secrets
                  key: STRIPE_SECRET
            - name: MIX_STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm-webapp.fullname" $ }}-env-secrets
                  key: MIX_STRIPE_KEY
            - name: MIX_STRIPE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm-webapp.fullname" $ }}-env-secrets
                  key: MIX_STRIPE_SECRET
            - name: STRIPE_USER_PLAN
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm-webapp.fullname" $ }}-env-secrets
                  key: STRIPE_USER_PLAN
            - name: STRIPE_TAX_RATE
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm-webapp.fullname" $ }}-env-secrets
                  key: STRIPE_TAX_RATE
            - name: EEX_SFTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm-webapp.fullname" $ }}-env-secrets
                  key: EEX_SFTP_USERNAME
            - name: EEX_SFTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm-webapp.fullname" $ }}-env-secrets
                  key: EEX_SFTP_PASSWORD
            - name: EEX_SFTP_REMOTE_PATH
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm-webapp.fullname" $ }}-env-secrets
                  key: EEX_SFTP_REMOTE_PATH
            - name: LOG_SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm-webapp.fullname" $ }}-env-secrets
                  key: LOG_SLACK_WEBHOOK_URL
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm-webapp.fullname" $ }}-env-secrets
                  key: SLACK_WEBHOOK_URL
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm-webapp.fullname" $ }}-redis
                  key: redis-password
          envFrom:
            - configMapRef:
                name: {{ include "helm-webapp.fullname" $ }}-config
          {{ end }}
          {{- end }}
      volumes:
        - name: {{ include "helm-webapp.fullname" . }}-storage
          persistentVolumeClaim:
            claimName: {{ include "helm-webapp.fullname" . }}-pv-claim
