apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: web-1222-ingress-route-tcp
  namespace: kuhdo-web-1222
spec:
  entryPoints:
    - websocket
  routes:
    - match: HostSNI(`web-1222.pr.kuhdo.dev`)
      services:
        - name: kuhdo-webapp-websockets
          port: 6001
  { { - if .Values.ingressRouteTCP.tls } }
  tls:
    { { - range .Values.ingressRouteTCP.tls } }
    - hosts:
        { { - range .hosts } }
        - { { . | quote } }
        { { - end } }
    { { - end } }
  { { - end } }