{{- if .Values.ingressRouteTCP.enabled -}}
{{- $fullName := include "helm-webapp.fullname" . -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "helm-webapp.labels" . | nindent 4 }}
spec:
  entryPoints:
    {{- range .Values.ingressRouteTCP.entryPoints }}
    - {{ . | quote }}
    {{- end }}
  {{- if .Values.ingressRouteTCP.tls }}
  tls:
    secretName: {{ .Values.ingressRouteTCP.tls.secretName }}
  {{- end }}
  routes:
    {{- range .Values.ingressRouteTCP.hosts }}
    - match: HostSNI(`{{ .host }}`)
      {{- $name := .name }}
      {{- $port := .port }}
      services:
        - name: {{ $fullName }}-{{ $name }}
          port: {{ $port }}
    {{- end }}
{{- end }}
