apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "helm-webapp.fullname" . }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-1"
    # "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/resource-policy": keep
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
      {{- include "helm-webapp.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: regcred
      containers:
        - name: db-migrations-seeds
          image: "{{ .Values.containers.app.repository}}:{{ .Values.containers.app.tag | default .Chart.AppVersion }}"
          command:
            - /bin/sh
            - -c
            {{ if .Values.tags.dynamic}}
            - php artisan db:wipe --force && php artisan migrate --seed --env=local --force && php artisan kuhdo:courses:current && php artisan kuhdo:courses:eod && php artisan cache:clear && php artisan storage:link && php artisan clear-compiled && php artisan view:clear && php artisan optimize
            {{- else }}
            - php artisan migrate --force && php artisan db:seed --force --class RolesPermissions && php artisan storage:link && php artisan clear-compiled && php artisan view:clear && php artisan optimize
            {{ end }}
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "helm-webapp.fullname" $ }}-config
                  key: DB_HOST
            {{- range $key, $value := .Values.secrets.webapp }}
            - name: {{ $key }}
              value: {{ $value }}
            {{ end -}}
            - name: APP_KEY
              value: {{ include "laravel.app_key" . }}
            - name: DB_DATABASE
              value: {{ .Values.secrets.database.MYSQL_DATABASE}}
            - name: DB_PASSWORD
              value: {{ .Values.secrets.database.MYSQL_PASSWORD}}
            - name: DB_USERNAME
              value: {{ .Values.secrets.database.MYSQL_USER}}
            {{ if eq (include "prodstaging" .) "true" -}}
            - name: REDIS_PASSWORD
              value: {{ .Values.secrets.redis.password}}
            {{ end }}
          envFrom:
            - configMapRef:
                name: {{ include "helm-webapp.fullname" $ }}-config