apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "helm-webapp.fullname" . }}
  labels:
  {{- include "helm-webapp.labels" . | nindent 4 }}
spec:
  {{- if .Values.nfsClientStorage.enabled }}
  storageClassName: nfs-client
  {{- end }}
  accessModes:
  {{- if .Values.nfsClientStorage.enabled }}
    - ReadWriteMany
  {{- else }}
    - ReadWriteOnce
  {{- end }}
  resources:
    requests:
      storage: 1Gi