apiVersion: v1
kind: Secret
metadata:
  name: {{include "helm-webapp.fullname" . }}-env-secrets
type: Opaque
data:
  APP_KEY: {{ include "laravel.app_key" . | b64enc | quote }}
  EEX_SFTP_PASSWORD: {{ .Values.secrets.webapp.EEX_SFTP_PASSWORD | b64enc }}
  EEX_SFTP_REMOTE_PATH: {{ .Values.secrets.webapp.EEX_SFTP_REMOTE_PATH | b64enc }}
  EEX_SFTP_USERNAME: {{ .Values.secrets.webapp.EEX_SFTP_USERNAME | b64enc }}
  LOG_SLACK_WEBHOOK_URL: {{ .Values.secrets.webapp.LOG_SLACK_WEBHOOK_URL | b64enc }}
  MAIL_PASSWORD: {{ .Values.secrets.webapp.MAIL_PASSWORD | b64enc }}
  MAILGUN_SECRET: {{ .Values.secrets.webapp.MAILGUN_SECRET | b64enc }}
  SLACK_WEBHOOK_URL: {{ .Values.secrets.webapp.SLACK_WEBHOOK_URL | b64enc }}
  PUSHER_APP_SECRET: {{ .Values.secrets.webapp.PUSHER_APP_SECRET | b64enc }}
---
apiVersion: v1
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-webapp.fullname" . }}-db-creds
type: Opaque
data:
  MYSQL_DATABASE: {{ ternary (randAlpha 10) .Values.secrets.database.MYSQL_DATABASE (empty .Values.secrets.database.MYSQL_DATABASE)  | b64enc | quote}}
  MYSQL_PASSWORD: {{  ternary (randAlphaNum 10) .Values.secrets.database.MYSQL_PASSWORD (empty .Values.secrets.database.MYSQL_PASSWORD) | b64enc | quote}}
  MYSQL_USER: {{ ternary (randAlpha 10) .Values.secrets.database.MYSQL_USER (empty .Values.secrets.database.MYSQL_USER) | b64enc | quote}}
  MYSQL_ROOT_PASSWORD: {{ ternary (randAlphaNum 10) .Values.secrets.database.MYSQL_ROOT_PASSWORD (empty .Values.secrets.database.MYSQL_ROOT_PASSWORD) | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-webapp.fullname" . }}-mariadb-galera-creds
type: Opaque
data:
  mariadb-password: {{ ternary (randAlphaNum 10) .Values.secrets.database.MYSQL_PASSWORD (empty .Values.secrets.database.MYSQL_PASSWORD) | b64enc | quote}}
  mariadb-root-password: {{ ternary (randAlphaNum 10) .Values.secrets.database.MYSQL_ROOT_PASSWORD (empty .Values.secrets.database.MYSQL_ROOT_PASSWORD) | b64enc | quote}}
  mariadb-galera-mariabackup-password: {{ ternary (randAlphaNum 10) .Values.secrets.database.MARIADB_GALERA_MARIABACKUP_PASSWORD (empty .Values.secrets.database.MARIADB_GALERA_MARIABACKUP_PASSWORD) | b64enc | quote}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-webapp.fullname" . }}-redis
type: Opaque
data:
  redis-password: {{ ternary (randAlphaNum 10) .Values.secrets.redis.password (empty .Values.secrets.redis.password) | b64enc | quote}}