apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-webapp.fullname" . | kebabcase }}-web
  labels:
    {{- include "helm-webapp.labels" . | nindent 4 }}
spec:
  type: {{  .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: {{ include "helm-webapp.fullname" .  | kebabcase }}-web
  selector:
    {{- include "helm-webapp.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-webapp.fullname" .  | kebabcase }}-app
  labels:
  {{- include "helm-webapp.labels" . | nindent 4 }}
spec:
  ports:
    - port: 9000
      protocol: TCP
      name: {{ include "helm-webapp.fullname" .  | kebabcase }}-app
  selector:
  {{- include "helm-webapp.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-webapp.fullname" . | kebabcase }}-websockets
  labels:
  {{- include "helm-webapp.labels" . | nindent 4 }}
spec:
  type: {{  .Values.service.type }}
  ports:
    - port: 6001
      protocol: TCP
      name: {{ include "helm-webapp.fullname" . | kebabcase }}-websockets
  selector:
  {{- include "helm-webapp.selectorLabels" . | nindent 4 }}