apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-webapp.fullname" . | kebabcase }}-web
  labels:
    {{- include "helm-webapp.labels" . | nindent 4 }}
spec:
  type: {{  .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helm-webapp.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-webapp.fullname" .  | kebabcase }}-app
  labels:
  {{- include "helm-webapp.labels" . | nindent 4 }}
spec:
  ports:
    - port: 9000
      targetPort: fpm
      protocol: TCP
      name: fpm
  selector:
  {{- include "helm-webapp.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-webapp.fullname" . | kebabcase }}-websocket
  labels:
  {{- include "helm-webapp.labels" . | nindent 4 }}
spec:
  type: {{  .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
  {{- include "helm-webapp.selectorLabels" . | nindent 4 }}
